//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessTimeApplication
    {
        public int AccessTimeApplicationId { get; set; }
        public int ApplicationId { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public Nullable<int> NbreJours { get; set; }
        public bool Statut { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
