//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddAppAccessLog
    {
        public int Id { get; set; }
        public string clientInfo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
