//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppNavigationPermission
    {
        public int AppNavigationPermissionId { get; set; }
        public int AppNavigationId { get; set; }
        public int PermissionId { get; set; }
        public Nullable<int> PermissionOrder { get; set; }
    
        public virtual AppNavigation AppNavigation { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
