//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compagnie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compagnie()
        {
            this.Agences = new HashSet<Agence>();
            this.Applications = new HashSet<Application>();
            this.UserCompagnies = new HashSet<UserCompagnie>();
        }
    
        public int CompagnieId { get; set; }
        public string NomCompagnie { get; set; }
        public string PersonneResponsable { get; set; }
        public string Adresse { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string AdresseElectronique { get; set; }
        public string PasswordEmail { get; set; }
        public Nullable<int> JourAvantResetPassword { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string NIF { get; set; }
        public byte[] SignatureResponsable { get; set; }
        public byte[] LogoCompagnie { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agence> Agences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCompagnie> UserCompagnies { get; set; }
    }
}
