//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GagnantLotterie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GagnantLotterie()
        {
            this.Paiements = new HashSet<Paiement>();
        }
    
        public int GagnantLotterieId { get; set; }
        public int TicketId { get; set; }
        public int TirageId { get; set; }
        public string BouleJouer { get; set; }
        public string BouleGagner { get; set; }
        public string JacpotBoule { get; set; }
        public int MontantGagner { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual Tirage Tirage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paiement> Paiements { get; set; }
    }
}
