//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivJwetla
    {
        public int LivJwetlaId { get; set; }
        public bool IsManmanBoulLa { get; set; }
        public int NbreBouleGagner { get; set; }
        public int PrixTicket { get; set; }
        public int MontantAPayer { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
    }
}
