//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointDeVente
    {
        public int PointDeVenteId { get; set; }
        public int CompagnieId { get; set; }
        public string NomPointDeVente { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string CodePostal { get; set; }
        public System.DateTime DateCreation { get; set; }
        public bool Statut { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public string CodePointDeVente { get; set; }
    
        public virtual Compagnie Compagnie { get; set; }
    }
}
