//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapportTirage
    {
        public int RapportTirageId { get; set; }
        public int TirageId { get; set; }
        public int NbreTicketGagant { get; set; }
        public int NbreTicketPerdant { get; set; }
        public decimal MontantTicketPerdant { get; set; }
        public decimal MontantTicketGagnant { get; set; }
        public decimal MontantTTotalJouer { get; set; }
        public decimal MontantAPayer { get; set; }
    
        public virtual Tirage Tirage { get; set; }
    }
}
