//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDetail
    {
        public int TicketDetailId { get; set; }
        public int TicketId { get; set; }
        public int Boule1Id { get; set; }
        public int Boule2Id { get; set; }
        public int Boule3Id { get; set; }
        public int Boule4Id { get; set; }
        public int Boule5Id { get; set; }
        public int Boule6Id { get; set; }
    
        public virtual Boule Boule { get; set; }
        public virtual Boule Boule1 { get; set; }
        public virtual Boule Boule2 { get; set; }
        public virtual Boule Boule3 { get; set; }
        public virtual Boule Boule4 { get; set; }
        public virtual Boule Boule5 { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
