//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.GagnantLotteries = new HashSet<GagnantLotterie>();
            this.TicketDetails = new HashSet<TicketDetail>();
        }
    
        public int TicketId { get; set; }
        public string CodeTicket { get; set; }
        public int UserPointDeVenteId { get; set; }
        public Nullable<int> TirageId { get; set; }
        public bool IsGagnant { get; set; }
        public bool IsDjapot { get; set; }
        public System.DateTime DateCreation { get; set; }
        public bool IsVente { get; set; }
        public Nullable<System.DateTime> DateVente { get; set; }
        public string BouleListes { get; set; }
        public Nullable<System.DateTime> DateTirage { get; set; }
        public string NomJoueur { get; set; }
        public string JacpotBoule { get; set; }
        public Nullable<int> Prix { get; set; }
        public Nullable<int> Tour { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GagnantLotterie> GagnantLotteries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketDetail> TicketDetails { get; set; }
        public virtual Tirage Tirage { get; set; }
        public virtual UserPointDeVente UserPointDeVente { get; set; }
    }
}
