//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TchotchoLoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserCompagnies = new HashSet<UserCompagnie>();
            this.UserPointDeVentes = new HashSet<UserPointDeVente>();
            this.UserPointDeVentes1 = new HashSet<UserPointDeVente>();
        }
    
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string LoweredUserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string LoweredEmail { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public byte[] ProfilPhoto { get; set; }
        public bool SuperUser { get; set; }
        public string SessionId { get; set; }
        public string OTP { get; set; }
        public Nullable<bool> Authenticated { get; set; }
        public Nullable<System.DateTime> AuthenticationDate { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCompagnie> UserCompagnies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPointDeVente> UserPointDeVentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPointDeVente> UserPointDeVentes1 { get; set; }
    }
}
